/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_R */
#define LED_R_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_0_INBUF_ENABLED 0u
#define LED_R_0_INIT_DRIVESTATE 1u
#define LED_R_0_INIT_MUXSEL 0u
#define LED_R_0_INPUT_SYNC 2u
#define LED_R_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_0_NUM 3u
#define LED_R_0_PORT GPIO_PRT0
#define LED_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_R_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_R_INBUF_ENABLED 0u
#define LED_R_INIT_DRIVESTATE 1u
#define LED_R_INIT_MUXSEL 0u
#define LED_R_INPUT_SYNC 2u
#define LED_R_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_R_NUM 3u
#define LED_R_PORT GPIO_PRT0
#define LED_R_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
