/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_LED_1 */
#define Pin_LED_1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED_1_0_INBUF_ENABLED 0u
#define Pin_LED_1_0_INIT_DRIVESTATE 1u
#define Pin_LED_1_0_INIT_MUXSEL 0u
#define Pin_LED_1_0_INPUT_SYNC 2u
#define Pin_LED_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED_1_0_NUM 6u
#define Pin_LED_1_0_PORT GPIO_PRT9
#define Pin_LED_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_LED_1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED_1_INBUF_ENABLED 0u
#define Pin_LED_1_INIT_DRIVESTATE 1u
#define Pin_LED_1_INIT_MUXSEL 0u
#define Pin_LED_1_INPUT_SYNC 2u
#define Pin_LED_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED_1_NUM 6u
#define Pin_LED_1_PORT GPIO_PRT9
#define Pin_LED_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_LED_2 */
#define Pin_LED_2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED_2_0_INBUF_ENABLED 0u
#define Pin_LED_2_0_INIT_DRIVESTATE 1u
#define Pin_LED_2_0_INIT_MUXSEL 8u
#define Pin_LED_2_0_INPUT_SYNC 2u
#define Pin_LED_2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED_2_0_NUM 4u
#define Pin_LED_2_0_PORT GPIO_PRT9
#define Pin_LED_2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED_2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_LED_2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED_2_INBUF_ENABLED 0u
#define Pin_LED_2_INIT_DRIVESTATE 1u
#define Pin_LED_2_INIT_MUXSEL 8u
#define Pin_LED_2_INPUT_SYNC 2u
#define Pin_LED_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED_2_NUM 4u
#define Pin_LED_2_PORT GPIO_PRT9
#define Pin_LED_2_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
