/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* CodecI2CM_SCB_IRQ */
    const cy_stc_sysint_t CodecI2CM_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)CodecI2CM_SCB_IRQ__INTC_NUMBER,
        .intrPriority = CodecI2CM_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* CapSense_ISR */
    const cy_stc_sysint_t CapSense_ISR_cfg = {
        .intrSrc = (IRQn_Type)CapSense_ISR__INTC_NUMBER,
        .intrPriority = CapSense_ISR__INTC_CORTEXM4_PRIORITY
    };

    /* DMA_I2S_IRQ */
    const cy_stc_sysint_t DMA_I2S_IRQ_cfg = {
        .intrSrc = (IRQn_Type)DMA_I2S_IRQ__INTC_NUMBER,
        .intrPriority = DMA_I2S_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* DMA_PDM_IRQ */
    const cy_stc_sysint_t DMA_PDM_IRQ_cfg = {
        .intrSrc = (IRQn_Type)DMA_PDM_IRQ__INTC_NUMBER,
        .intrPriority = DMA_PDM_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* SMIF_1_SMIF_IRQ */
    const cy_stc_sysint_t SMIF_1_SMIF_IRQ_cfg = {
        .intrSrc = (IRQn_Type)SMIF_1_SMIF_IRQ__INTC_NUMBER,
        .intrPriority = SMIF_1_SMIF_IRQ__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

