/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* DMA_I2S_IRQ */
#define DMA_I2S_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define DMA_I2S_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define DMA_I2S_IRQ__INTC_NUMBER 50u
#define DMA_I2S_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define DMA_I2S_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define DMA_I2S_IRQ_INTC_NUMBER 50u

/* DMA_PDM_IRQ */
#define DMA_PDM_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define DMA_PDM_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define DMA_PDM_IRQ__INTC_NUMBER 51u
#define DMA_PDM_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define DMA_PDM_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define DMA_PDM_IRQ_INTC_NUMBER 51u

/* CapSense_ISR */
#define CapSense_ISR__INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR__INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR__INTC_NUMBER 49u
#define CapSense_ISR_INTC_CORTEXM4_ASSIGNED 1
#define CapSense_ISR_INTC_CORTEXM4_PRIORITY 7u
#define CapSense_ISR_INTC_NUMBER 49u

/* SMIF_1_SMIF_IRQ */
#define SMIF_1_SMIF_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define SMIF_1_SMIF_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define SMIF_1_SMIF_IRQ__INTC_NUMBER 142u
#define SMIF_1_SMIF_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define SMIF_1_SMIF_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define SMIF_1_SMIF_IRQ_INTC_NUMBER 142u

/* CodecI2CM_SCB_IRQ */
#define CodecI2CM_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define CodecI2CM_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define CodecI2CM_SCB_IRQ__INTC_NUMBER 44u
#define CodecI2CM_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define CodecI2CM_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define CodecI2CM_SCB_IRQ_INTC_NUMBER 44u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
